include: package:lints/recommended.yaml

analyzer:
  language:
    # would be good to turn these on in future
    strict-inference: false
    strict-casts: false
    strict-raw-types: false
  errors:
    todo: ignore

linter:
  rules:
    camel_case_types: false
    non_constant_identifier_names: false
    always_put_control_body_on_new_line: false
    curly_braces_in_flow_control_structures: false
    prefer_final_locals: false
    constant_identifier_names: false
    avoid_renaming_method_parameters: false
    prefer_function_declarations_over_variables: false
    avoid_function_literals_in_foreach_calls: false
    no_leading_underscores_for_local_identifiers: false
