name: dart_eval
description: A flexible Dart bytecode compiler and interpreter written in Dart, enabling code push for AOT Dart apps.
version: 0.5.4
homepage: https://github.com/ethanblake4/dart_eval
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  dart_eval:

dependencies:
   args: ^2.3.0
   analyzer: ^5.0.0
   collection: ^1.15.0
   dcli: ^1.34.0
   json_annotation: ^4.4.0
   directed_graph: ^0.3.7
   _fe_analyzer_shared: '>=50.0.0'

dev_dependencies:
  test: ^1.21.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  lints: ^1.0.0
