name: dart_eval
description: A flexible Dart bytecode compiler and runtime written in Dart, enabling code push for AOT Dart apps.
version: 0.3.0
homepage: https://github.com/ethanblake4/dart_eval

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
   args: ^2.3.0
   analyzer: ^3.0.0
   collection: ^1.15.0
   dcli: ^1.15.5
   json_annotation: ^4.4.0
   directed_graph: ^0.3.7

dev_dependencies:
  test: ^1.17.12
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  lints: ^1.0.0
