name: dart_eval
description: A flexible Dart bytecode compiler and interpreter written in Dart, enabling code push for AOT Dart apps.
version: 0.6.2
homepage: https://github.com/ethanblake4/dart_eval
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.17.0 <4.0.0'

executables:
  dart_eval:

dependencies:
  args: ^2.3.0
  analyzer: ^6.0.0
  collection: ^1.15.0
  directed_graph: ^0.3.0
  json_annotation: ^4.4.0
  pubspec_parse: ^1.2.0
  path: ^1.8.0
  pub_semver: ^2.1.0

dev_dependencies:
  test: ^1.21.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  lints: ^2.0.1
